[metadata]
name = mypackage

[importlinter]
root_package = mypackage
include_external_packages = True

[importlinter:contract:layers]
name = Web on top of the domain
type = layers
layers =
    mypackage.web
    mypackage.domain

[importlinter:contract:pure-domain]
name = The domain stays pure
type = forbidden
source_modules =
    mypackage.domain
forbidden_modules =
    mypackage.legacy
    pydantic
